### ISSUE TITLE
Module build failed: Error: [mobx] 'default' is no longer part of the public MobX api.

### ISSUE THREAD

**Issue by 0x1428571429** [zwhitchcox/babel-preset-mobx#2]
Module build failed: Error: [mobx] 'default' is no longer part of the public MobX api. Please consult the changelog to find out where this functionality went (While processing preset: "/Users/Fan/workspace/micro-react-scaffold/node_modules/_mobx@4.0.2@mobx/lib/mobx.js")

**Comment by rossipedia** [comment]
With mobx v4, there is no longer a default export for mobx. You will need to use:

``` js
import * as mobx from 'mobx';
```

instead of

``` js
import mobx from 'mobx';
```

Closing as this is not actually an issue with the babel preset.
